### ISSUE TITLE
Syntax error: unexpected end of file in .ipynb file

### ISSUE THREAD

**Issue by jasvinderk** [MunibaFaiza/Free_Energy_Landscape-MD#2]
Hi

Getting error in the second last step: 
./FEL_Time_Frame_Extractor_CaseI.ipynb: line 267: syntax error: unexpected end of file

Tried to validate and confirm the bracket use but could'nt resolve the issue.

Timely help will be very much appreciated ☺️

**Comment by jasvinderk** [comment]
I could do it using Jupytor but .txt file is not getting generated :(

**Comment by MunibaFaiza** [comment]
Hi,

Are you able to see minima points on the plot?

**Comment by jasvinderk** [comment]
![free_energy_landscape_with_minima](https://github.com/user-attachments/assets/0c5d307d-7aea-4f40-93fd-d4061247f538)
Thank you for the prompt response...
yes minima is there, not very sharp though,.....am I doing it correctly? this is a REMD simulation run for a particular temperature with protein.

**Comment by MunibaFaiza** [comment]
I don't see how the text file is not getting generated. It is generated in any case whether there are time frames or not. Check your directory carefully. it should be there.

**Comment by jasvinderk** [comment]
Thank you for your response. I did check it carefully, is there anything that needs to be installed for it to work properly? I see another user having the same trouble.
Help would be much appreciated!

**Comment by MunibaFaiza** [comment]
Hi, 

Another user was not getting time frames because she was using small MD data but her file was getting generated. 

Install evrything, perform all the previous steps carefully as mentioned in the following article, then use the Python scripts from the package. 

https://bioinformaticsreview.com/20240228/free_energy_landscape-md-python-package-to-create-free-energy-landscape-using-pca-from-gromacs/

Read the article carefully, you will find everything in there. 

Closing this issue now.
